// Chat styles extracted from page.tsx
const styles = {
  chatApp: {
    display: 'flex',
    height: '100vh',
    background: '#13161d',
    color: '#fff',
    fontFamily: 'Inter, system-ui, sans-serif',
    overflow: 'hidden',
  } as React.CSSProperties,
  sidebar: {
    width: '260px',
    background: '#13161d',
    borderRight: '1px solid #2d323e',
    display: 'flex',
    flexDirection: 'column',
    padding: '20px 0',
  } as React.CSSProperties,
  navItem: (isActive: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 20px',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.2s',
    background: isActive ? '#2d323e' : 'transparent',
    color: isActive ? '#fff' : '#9ca3af',
    borderLeft: isActive ? '4px solid #3b82f6' : '4px solid transparent',
  }),
  chatPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    background: '#f0f2f5',
  } as React.CSSProperties,
  chatHeader: {
    padding: '15px 25px',
    background: '#1a1d26',
    borderBottom: '1px solid #2d323e',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: '#fff',
  } as React.CSSProperties,
  messagesContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '25px',
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  } as React.CSSProperties,
  messageBubble: (isSent: boolean): React.CSSProperties => ({
    maxWidth: '75%',
    padding: '12px 16px',
    borderRadius: '12px',
    fontSize: '14px',
    alignSelf: isSent ? 'flex-end' : 'flex-start',
    background: isSent ? '#3b82f6' : '#fff',
    color: isSent ? '#fff' : '#1f2937',
    boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
  }),
  rightPanel: {
    width: '300px',
    background: '#13161d',
    borderLeft: '1px solid #2d323e',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '25px',
  } as React.CSSProperties,
  inputForm: {
    padding: '15px 25px',
    background: '#fff',
    borderTop: '1px solid #e5e7eb',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  } as React.CSSProperties,
  textarea: {
    flex: 1,
    border: 'none',
    outline: 'none',
    resize: 'none',
    fontSize: '14px',
    background: 'transparent',
    color: '#1f2937',
  } as React.CSSProperties,
};

export default styles;
